# Generated by Django 6.0.4 on 2026-05-04 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('english_words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(auto_now_add=True, verbose_name='avaliada em')),
                ('questions_requested', models.PositiveSmallIntegerField(verbose_name='quantidade de perguntas')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-tested_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='minha resposta')),
                ('is_correct', models.BooleanField(default=False, verbose_name='acertou')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='evaluations.evaluation', verbose_name='avaliação')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_items', to='english_words.englishword', verbose_name='palavra')),
            ],
            options={
                'verbose_name': 'Item de avaliação',
                'verbose_name_plural': 'Itens de avaliação',
                'ordering': ['id'],
            },
        ),
    ]
