# Generated by Django 6.0.4 on 2026-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=120, verbose_name='palavra')),
                ('meaning', models.TextField(verbose_name='significado')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
            ],
            options={
                'verbose_name': 'Palavra em inglês',
                'verbose_name_plural': 'Palavras em inglês',
                'ordering': ['word'],
            },
        ),
    ]
