# Generated by Django 6.0.4 on 2026-05-04 23:10

import django.db.models.deletion
from django.db import migrations, models


def forward_copy_meanings(apps, schema_editor):
    EnglishWord = apps.get_model('english_words', 'EnglishWord')
    EnglishMeaning = apps.get_model('english_words', 'EnglishMeaning')

    for word in EnglishWord.objects.all():
        meaning = getattr(word, 'meaning', '')
        if meaning:
            EnglishMeaning.objects.create(word=word, text=meaning)


def reverse_copy_meanings(apps, schema_editor):
    EnglishWord = apps.get_model('english_words', 'EnglishWord')

    for word in EnglishWord.objects.all():
        first_meaning = word.meanings.order_by('id').values_list('text', flat=True).first()
        if first_meaning:
            word.meaning = first_meaning
            word.save(update_fields=['meaning'])


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='significado')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meanings', to='english_words.englishword', verbose_name='palavra')),
            ],
            options={
                'verbose_name': 'Significado',
                'verbose_name_plural': 'Significados',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(forward_copy_meanings, reverse_copy_meanings),
        migrations.RemoveField(
            model_name='englishword',
            name='meaning',
        ),
    ]
