# Generated by Django 6.0.4 on 2026-05-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='projeto padrão'),
        ),
    ]
