image: python:3.7-slim-buster

stages:
  - restoredbfromprod
  - analysis
  # - test
  - release
  - deploy

flake8:
  stage: analysis
  script:
    - pip install flake8
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --max-complexity=10 --max-line-length=80 --statistics --exclude migrations
  tags:
    - docker

# pytest:
#   stage: test
#   script:
#     - pip install -r requirements.txt
#     - pip freeze
#     - pip install pytest
#     - pytest
#   allow_failure: false
#   tags:
#     - docker


.configure_docker:
  image: docker:stable
  services:
  - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  after_script:
    - docker logout $CI_REGISTRY
  tags:
    - docker

release:homolog:
  stage: release
  extends:
    - .configure_docker
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: manual
  script:
    - docker build
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY_IMAGE:latest
      --target homolog .

    - docker build
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-worker
      -t $CI_REGISTRY_IMAGE:latest-worker
      --target worker-homolog .

    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA-worker
    - docker push $CI_REGISTRY_IMAGE:latest-worker

release:production:
  stage: release
  extends:
    - .configure_docker
  rules:
  - if: $CI_COMMIT_TAG
    when: always
  script:
    - docker build
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
      -t $CI_REGISTRY_IMAGE:latest
      --target prod .

    - docker build
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-worker
      -t $CI_REGISTRY_IMAGE:latest-worker
      --target worker .

    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-worker
    - docker push $CI_REGISTRY_IMAGE:latest-worker

.configure_ssh:
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

.configure_ssh_local_server:
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_LOCAL_SERVER" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "$SSH_SERVER_HOSTKEYS_LOCAL_SERVER" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

.configure_ssh_prod:
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - echo "$SSH_SERVER_HOSTKEYS_PROD" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

full_deploy:homolog:
  stage: deploy
  image: alpine
  extends:
    - .configure_ssh
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: manual
  script:
    - ssh orti@104.131.26.160 /home/orti/scripts/better_than_yesterday/full_deploy_backend.sh
    - echo "Full deploy"
  tags:
    - docker

deploy:homolog:
  stage: deploy
  image: alpine
  extends:
    - .configure_ssh
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: manual
  script:
    - ssh orti@104.131.26.160 /home/orti/scripts/better_than_yesterday/deploy_backend.sh
    - echo "Only Code deploy"
  tags:
    - docker

deploy:homolog-local-server:
  stage: deploy
  image: alpine
  extends:
    - .configure_ssh_local_server
  rules:
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: manual
  script:
    - ssh administrador@187.19.204.160 -p 5673 /home/administrador/scripts/better_than_yesterday/deploy_backend.sh latest
    - echo "Only Code deploy"
  tags:
    - docker

deploy:production:
  stage: deploy
  image: alpine
  extends:
    - .configure_ssh_prod
  rules:
    - if: $CI_COMMIT_TAG
      when: manual
  script:
    - ssh better_than_yesterday@143.198.16.232 /home/better_than_yesterday/scripts/deploy_backend.sh $CI_COMMIT_TAG
    - echo "Code deploy $CI_COMMIT_TAG"
  tags:
    - docker

restore_db_from_prod_to_homolog:
  stage: restoredbfromprod
  image: alpine
  extends:
    - .configure_ssh
  script:
    - ssh orti@104.131.26.160 /home/orti/scripts/better_than_yesterday/sync_files_from_prod.sh
    - echo "DB Restored"
  when: manual
  needs: []
  tags:
    - docker
