[tox]
envlist = {3.5}

[testenv:functional]
basepython = python3
deps = -r{toxinidir}/requirements_test.txt
        nose
        coverage
commands =
    coverage run --source=better_than_yesterday -m unittest discover better_than_yesterday

[flake8]
max-line-length=80
max-complexity=10
