# Generated by Django 6.0.4 on 2026-04-23 16:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(verbose_name='descrição')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1, verbose_name='prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='status')),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='porcentagem de conclusão')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'Tarefa de projeto',
                'verbose_name_plural': 'Tarefas de projeto',
                'ordering': ['project__title', '-priority', 'title'],
            },
        ),
    ]
