# Generated by Django 6.0.4 on 2026-04-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttask',
            options={'ordering': ['-priority', 'title'], 'verbose_name': 'Tarefa de projeto', 'verbose_name_plural': 'Tarefas de projeto'},
        ),
    ]
