"""24.07.25 - migracao inicial

Revision ID: 16cb6c7d753f
Revises:
Create Date: 2024-07-25 10:52:03.430435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16cb6c7d753f'
down_revision = None
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('description', sa.String(
                        length=1000), nullable=False),
                    sa.Column('settings', sa.Text(),
                              server_default='{}', nullable=False),
                    sa.Column('customized', sa.Boolean(),
                              server_default='false', nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name', name='application_name_uk')
                    )
    op.create_table('domain',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('application_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('display_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('doc', sa.String(length=60), nullable=True),
                    sa.Column('description', sa.String(
                        length=1000), nullable=True),
                    sa.Column('logo_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('parent_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('settings', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['application_id'], [
                                            'application.id'], ),
                    sa.ForeignKeyConstraint(['parent_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('file_infosys',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('image',
                    sa.Column('id', sa.CHAR(length=32), nullable=False),
                    sa.Column('type_image', sa.String(
                        length=100), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['file_infosys.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('functionality',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('code', sa.Numeric(precision=10), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('description', sa.String(
                        length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('ibge_sync',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('module',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('code', sa.Numeric(precision=10), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('description', sa.String(
                        length=1000), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('pais',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('codigo', sa.Numeric(
                        precision=5, scale=0), nullable=False),
                    sa.Column('nome', sa.String(length=80), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('codigo'),
                    sa.UniqueConstraint('codigo')
                    )
    op.create_table('project_cost',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('name', sa.String(length=30), nullable=False),
                    sa.Column('cost', sa.Numeric(
                        precision=13, scale=3), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('regiao',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('codigo_ibge', sa.Numeric(
                        precision=1, scale=0), nullable=False),
                    sa.Column('sigla', sa.CHAR(length=2), nullable=False),
                    sa.Column('nome', sa.String(length=20), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('sigla'),
                    sa.UniqueConstraint('sigla')
                    )
    op.create_table(
        'role',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column(
            'data_view',
            sa.Enum('MULTI_DOMAIN', 'DOMAIN',
                    name='roledataviewtype'), server_default='DOMAIN',
            nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', name='role_name_uk')
    )
    op.create_table('route',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('url', sa.String(length=80), nullable=False),
                    sa.Column('method', sa.String(length=10), nullable=False),
                    sa.Column('bypass', sa.Boolean(), nullable=False),
                    sa.Column('sysadmin', sa.Boolean(), nullable=False),
                    sa.Column('projeto', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('url', 'method', name='route_uk')
                    )
    op.create_table('capability',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('route_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('application_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.ForeignKeyConstraint(['application_id'], [
                                            'application.id'], ),
                    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'route_id', 'application_id', name='capability_uk')
                    )
    op.create_table(
        'capability_functionality',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('functionality_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('application_id', sa.CHAR(
            length=32), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], [
            'application.id'], ),
        sa.ForeignKeyConstraint(['functionality_id'], [
            'functionality.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('functionality_id', 'application_id',
                            name='cp_functionality_id_application_id_uk')
    )
    op.create_table('capability_module',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('module_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('application_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.ForeignKeyConstraint(['application_id'], [
                                            'application.id'], ),
                    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('module_id', 'application_id',
                                        name='cp_module_id_application_id_uk')
                    )
    op.create_table(
        'constant_for_calculation',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('application_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('table_name', sa.String(
            length=60), nullable=False),
        sa.Column('p_processos', sa.Numeric(
            precision=5), nullable=False),
        sa.Column('p_acessos_db', sa.Numeric(
            precision=5), nullable=False),
        sa.ForeignKeyConstraint(['application_id'], [
            'application.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'application_id', 'table_name',
            name='constant_for_calculation_application_id_table_name_uk')
    )
    op.create_table(
        'domain_and_table_sequence',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('table_id', sa.String(
            length=100), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Numeric(
            precision=10), nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'name', 'table_id', 'domain_id',
            name='domain_and_table_sequence_name_table_id_domain_id_uk')
    )
    op.create_table('domain_contact',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('contact', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table(
        'domain_sequence',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('value', sa.Numeric(
            precision=10), nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name', 'domain_id',
                            name='domain_sequence_name_domain_id_uk')
    )
    op.create_table(
        'file_sync',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('file_id', sa.CHAR(length=32), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'ERROR',
                                    name='file_sync_status'), nullable=False),
        sa.Column('entity', sa.String(length=80), nullable=False),
        sa.Column('entity_id', sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(['file_id'], ['file_infosys.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'functionality_route',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('functionality_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('route_id', sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(['functionality_id'], [
            'functionality.id'], ),
        sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'functionality_id', 'route_id',
            name='functionality_route_functionality_id_route_id_uk')
    )
    op.create_table('ibge_sync_message',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('ibge_sync_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('type', sa.Enum('Info', 'Warning', 'Error',
                                              name='messagetype'),
                              nullable=False),
                    sa.Column('body', sa.String(length=250), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['ibge_sync_id'], ['ibge_sync.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table(
        'module_functionality',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('module_id', sa.CHAR(length=32), nullable=False),
        sa.Column('functionality_id', sa.CHAR(
            length=32), nullable=False),
        sa.ForeignKeyConstraint(['functionality_id'], [
            'functionality.id'], ),
        sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'module_id', 'functionality_id',
            name='module_functionality_module_id_functionality_id_uk')
    )
    op.create_table('tag',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.Column('color', sa.CHAR(length=7), nullable=False),
                    sa.Column('description', sa.String(
                        length=1024), nullable=False),
                    sa.Column('tag_name', sa.String(length=60), nullable=False),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('domain_id', 'name',
                                        name='tag_domain_id_name_uk'),
                    sa.UniqueConstraint('domain_id', 'tag_name',
                                        name='tag_domain_id_tag_name_uk')
                    )
    op.create_table('timeline_event',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('event_at', sa.DateTime(), nullable=False),
                    sa.Column('event_by', sa.CHAR(length=32), nullable=False),
                    sa.Column('lat', sa.Numeric(
                        precision=14, scale=8), nullable=False),
                    sa.Column('lon', sa.Numeric(
                        precision=14, scale=8), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('entity', sa.String(length=100), nullable=True),
                    sa.Column('entity_id', sa.CHAR(length=32), nullable=True),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('uf',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('regiao_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('codigo_ibge', sa.Numeric(
                        precision=2, scale=0), nullable=False),
                    sa.Column('sigla', sa.CHAR(length=2), nullable=False),
                    sa.Column('nome', sa.String(length=20), nullable=False),
                    sa.ForeignKeyConstraint(['regiao_id'], ['regiao.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('sigla'),
                    sa.UniqueConstraint('sigla')
                    )
    op.create_table('user',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=False),
                    sa.Column('nickname', sa.String(length=80), nullable=True),
                    sa.Column('email', sa.String(length=80), nullable=False),
                    sa.Column('password', sa.String(length=64), nullable=False),
                    sa.Column('photo_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('settings', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(['photo_id'], ['image.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email', 'domain_id',
                                        name='user_email_domain_id_uk'),
                    sa.UniqueConstraint('name', 'domain_id',
                                        name='user_name_domain_id_uk')
                    )
    op.create_table(
        'file_sync_message',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('file_sync_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('type_message', sa.Enum('INFO', 'WARNING', 'ERROR',
                                          name='file_sync_message_type'),
                  nullable=False),
        sa.Column('body', sa.String(length=250), nullable=False),
        sa.ForeignKeyConstraint(
            ['file_sync_id'], ['file_sync.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grant',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('mesorregiao',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('uf_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('codigo_ibge', sa.Numeric(
                        precision=4, scale=0), nullable=False),
                    sa.Column('nome', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['uf_id'], ['uf.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('codigo_ibge')
                    )
    op.create_table('notification',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('subject', sa.String(length=50), nullable=False),
                    sa.Column('body', sa.String(length=250), nullable=False),
                    sa.Column('read_date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table(
        'parceiro',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('cpf_cnpj', sa.CHAR(length=14), nullable=True),
        sa.Column('doc_estrangeiro', sa.CHAR(
            length=20), nullable=True),
        sa.Column('rg_insc_est', sa.String(
            length=20), nullable=True),
        sa.Column('nome_razao_social', sa.String(
            length=60), nullable=False),
        sa.Column('apelido_nome_fantasia',
                  sa.String(length=60), nullable=True),
        sa.Column('observacao', sa.String(
            length=500), nullable=True),
        sa.Column('data_nascimento', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.CHAR(length=32), nullable=True),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain_id', 'cpf_cnpj',
                            name='parceiro_domain_id_cpf_cnpj_uk'),
        sa.UniqueConstraint('domain_id', 'doc_estrangeiro',
                            name='parceiro_domain_id_doc_estrangeiro_uk'),
        sa.UniqueConstraint('domain_id', 'rg_insc_est',
                            name='parceiro_domain_id_rg_insc_est_uk'),
        sa.UniqueConstraint('user_id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_table('policy',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('capability_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('role_id', sa.CHAR(length=32), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['capability_id'], ['capability.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'capability_id', 'role_id', name='policy_uk')
                    )
    op.create_table(
        'policy_functionality',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('capability_functionality_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('role_id', sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(['capability_functionality_id'], [
            'capability_functionality.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('capability_functionality_id', 'role_id',
                            name='pf_capability_functionality_id_role_id_uk')
    )
    op.create_table(
        'policy_module',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('capability_module_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('role_id', sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(['capability_module_id'], [
            'capability_module.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('capability_module_id', 'role_id',
                            name='pm_capability_module_id_role_id_uk')
    )
    op.create_table('timeline_event_user',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('timeline_event_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['timeline_event_id'], [
                                            'timeline_event.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('token',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('natureza', sa.String(length=20), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cliente',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('codigo', sa.Numeric(
                        precision=10), nullable=False),
                    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(['id'], ['parceiro.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('domain_id', 'codigo',
                                        name='cliente_domain_id_codigo_uk')
                    )
    op.create_table('microrregiao',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('mesorregiao_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('codigo_ibge', sa.Numeric(
                        precision=5, scale=0), nullable=False),
                    sa.Column('nome', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['mesorregiao_id'], [
                                            'mesorregiao.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('codigo_ibge')
                    )
    op.create_table('parceiro_contato',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('parceiro_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('contato', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('municipio',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('microrregiao_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('codigo_ibge', sa.Numeric(
                        precision=7, scale=0), nullable=False),
                    sa.Column('nome', sa.String(length=50), nullable=False),
                    sa.Column('sigla_uf', sa.CHAR(length=2), nullable=False),
                    sa.Column('cep', sa.CHAR(length=8), nullable=True),
                    sa.ForeignKeyConstraint(['microrregiao_id'], [
                                            'microrregiao.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('cep'),
                    sa.UniqueConstraint('cep'),
                    sa.UniqueConstraint('codigo_ibge'),
                    sa.UniqueConstraint('codigo_ibge')
                    )
    op.create_table('domain_address',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('municipio_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('pais_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('logradouro', sa.String(
                        length=255), nullable=False),
                    sa.Column('numero', sa.String(length=60), nullable=False),
                    sa.Column('complemento', sa.String(
                        length=60), nullable=True),
                    sa.Column('bairro', sa.String(length=60), nullable=False),
                    sa.Column('ponto_referencia', sa.String(
                        length=512), nullable=True),
                    sa.Column('cep', sa.CHAR(length=8), nullable=False),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(
                        ['municipio_id'], ['municipio.id'], ),
                    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('parceiro_endereco',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('logradouro', sa.String(
                        length=255), nullable=False),
                    sa.Column('numero', sa.String(length=60), nullable=False),
                    sa.Column('complemento', sa.String(
                        length=60), nullable=True),
                    sa.Column('bairro', sa.String(length=60), nullable=False),
                    sa.Column('ponto_referencia', sa.String(
                        length=512), nullable=True),
                    sa.Column('cep', sa.CHAR(length=8), nullable=False),
                    sa.Column('municipio_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('pais_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('parceiro_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['municipio_id'], ['municipio.id'], ),
                    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
                    sa.ForeignKeyConstraint(['parceiro_id'], ['parceiro.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###

    op.create_foreign_key(
        'domain_image_id_fkey', 'domain', 'image',
        ['logo_id'], ['id'])


def downgrade():
    op.drop_constraint('domain_image_id_fkey',
                       'domain', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parceiro_endereco')
    op.drop_table('domain_address')
    op.drop_table('municipio')
    op.drop_table('parceiro_contato')
    op.drop_table('microrregiao')
    op.drop_table('cliente')
    op.drop_table('token')
    op.drop_table('timeline_event_user')
    op.drop_table('policy_module')
    op.drop_table('policy_functionality')
    op.drop_table('policy')
    op.drop_table('parceiro')
    op.drop_table('notification')
    op.drop_table('mesorregiao')
    op.drop_table('grant')
    op.drop_table('file_sync_message')
    op.drop_table('user')
    op.drop_table('uf')
    op.drop_table('timeline_event')
    op.drop_table('tag')
    op.drop_table('module_functionality')
    op.drop_table('ibge_sync_message')
    op.drop_table('functionality_route')
    op.drop_table('file_sync')
    op.drop_table('domain_sequence')
    op.drop_table('domain_contact')
    op.drop_table('domain_and_table_sequence')
    op.drop_table('constant_for_calculation')
    op.drop_table('capability_module')
    op.drop_table('capability_functionality')
    op.drop_table('capability')
    op.drop_table('route')
    op.drop_table('role')
    op.drop_table('regiao')
    op.drop_table('project_cost')
    op.drop_table('pais')
    op.drop_table('module')
    op.drop_table('image')
    op.drop_table('ibge_sync')
    op.drop_table('functionality')
    op.drop_table('file_infosys')
    op.drop_table('domain')
    op.drop_table('application')
    # ### end Alembic commands ###

    session = create_session(op)
    session.execute("""
        DROP TYPE IF EXISTS file_sync_message_type;
        DROP TYPE IF EXISTS file_sync_status;
        DROP TYPE IF EXISTS messagetype;
        DROP TYPE IF EXISTS roledataviewtype;
        """)
