"""25.02.10 - Adiciona status em conta_energia

Revision ID: 1ca349b9e2b0
Revises: a265304a610c
Create Date: 2025-02-10 21:27:41.415779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca349b9e2b0'
down_revision = 'a265304a610c'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    session = create_session(op)
    session.execute("DELETE FROM conta_energia;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conta_energia_evento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_energia_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column(
            'status',
            sa.Enum('CRIADA', 'CONFERIDA', 'PENDENTE', 'CONFIRMADA',
                    'CANCELADA', name='conta_energia_status'),
            server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conta_energia_id'], [
            'conta_energia.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'conta_energia',
        sa.Column('status', sa.Enum('CRIADA', 'CONFERIDA', 'PENDENTE',
                  'CONFIRMADA', 'CANCELADA', name='conta_energia_status'),
                  server_default='CRIADA', nullable=False))
    op.add_column('conta_energia', sa.Column(
        'status_por', sa.String(length=32), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'status_dh', sa.DateTime(), nullable=False))
    op.drop_constraint('pix_domain_id_chave_pix_uk', 'pix', type_='unique')
    op.create_unique_constraint(
        'pix_domain_id_tarefa_id_chave_pix_uk', 'pix', [
            'domain_id', 'tarefa_id', 'chave_pix'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'pix_domain_id_tarefa_id_chave_pix_uk', 'pix', type_='unique')
    op.create_unique_constraint('pix_domain_id_chave_pix_uk', 'pix', [
                                'domain_id', 'chave_pix'])
    op.drop_column('conta_energia', 'status_dh')
    op.drop_column('conta_energia', 'status_por')
    op.drop_column('conta_energia', 'status')
    op.drop_table('conta_energia_evento')
    # ### end Alembic commands ###
