"""25.01.29 - Adiciona pacote do financeiro

Revision ID: 3484a02b975f
Revises: 4ceebba15ada
Create Date: 2025-01-29 20:18:05.274947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3484a02b975f'
down_revision = '4ceebba15ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'centro_resultado',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('centro_resultado_id', sa.CHAR(
            length=32), nullable=True),
        sa.Column('descricao', sa.String(
            length=255), nullable=False),
        sa.ForeignKeyConstraint(['centro_resultado_id'], [
            'centro_resultado.id'], ),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'condicao_pagamento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('codigo', sa.Numeric(
            precision=3), nullable=False),
        sa.Column('descricao', sa.String(
            length=60), nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'codigo',
            name='condicao_pagamento_domain_id_tarefa_id_codigo_uk')
    )
    op.create_table(
        'instituicao_pagamento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('cnpj', sa.String(length=14), nullable=False),
        sa.Column('descricao', sa.String(
            length=100), nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'cnpj',
            name='instituicao_pagamento_domain_id_tarefa_id_cnpj_uk')
    )
    op.create_table(
        'natureza_financeira',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('natureza_financeira_id',
                  sa.CHAR(length=32), nullable=True),
        sa.Column('descricao', sa.String(
            length=255), nullable=False),
        sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA',
                                  name='natureza_financeira_tipo'),
                  nullable=False),
        sa.Column('periodicidade', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.ForeignKeyConstraint(['natureza_financeira_id'], [
            'natureza_financeira.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'pix',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('nome', sa.String(length=60), nullable=False),
        sa.Column('chave_pix', sa.String(
            length=60), nullable=False),
        sa.Column('cidade', sa.String(length=60), nullable=False),
        sa.Column('padrao', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain_id', 'chave_pix',
                            name='pix_domain_id_chave_pix_uk')
    )
    op.create_table(
        'portador',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('tipo', sa.Enum('INTERNO', 'EXTERNO',
                                  name='portadortipo'), nullable=False),
        sa.Column('descricao', sa.String(
            length=100), nullable=False),
        sa.Column('padrao', sa.Boolean(), nullable=False),
        sa.Column('codigo_banco', sa.CHAR(length=3), nullable=True),
        sa.Column('nome_banco', sa.String(
            length=100), nullable=True),
        sa.Column('numero_conta', sa.String(
            length=20), nullable=True),
        sa.Column('digito_conta', sa.CHAR(length=1), nullable=True),
        sa.Column('codigo_agencia', sa.String(
            length=20), nullable=True),
        sa.Column('digito_agencia', sa.CHAR(
            length=1), nullable=True),
        sa.Column('saldo', sa.Numeric(precision=15, scale=2),
                  server_default='0.0', nullable=False),
        sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2),
                  server_default='0.0', nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_pagar',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('portador_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('centro_resultado_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('natureza_financeira_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('numero', sa.Numeric(
            precision=10), nullable=False),
        sa.Column('numero_doc', sa.String(
            length=50), nullable=True),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('observacao', sa.String(
            length=500), nullable=True),
        sa.Column(
            'status',
            sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                    name='contapagarstatus'),
            server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.String(
            length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('valor_juros', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('valor_multa', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('valor_mora', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('origem', sa.String(length=5), nullable=False),
        sa.Column('serie', sa.Numeric(precision=10), nullable=True),
        sa.Column('desconto', sa.Numeric(precision=5, scale=2),
                  server_default='0', nullable=False),
        sa.ForeignKeyConstraint(['centro_resultado_id'], [
            'centro_resultado.id'], ),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.ForeignKeyConstraint(['natureza_financeira_id'], [
            'natureza_financeira.id'], ),
        sa.ForeignKeyConstraint(['portador_id'], ['portador.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'numero',
            name='conta_pagar_domain_id_tarefa_id_numero_uk')
    )
    op.create_index('ix_conta_pagar_numero', 'conta_pagar',
                    ['domain_id', 'numero'], unique=True)
    op.create_table(
        'forma_pagamento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('instituicao_pagamento_id',
                  sa.CHAR(length=32), nullable=True),
        sa.Column('codigo', sa.Numeric(
            precision=3), nullable=False),
        sa.Column('nome', sa.String(length=30), nullable=False),
        sa.Column('indicador_operacao', sa.String(), nullable=True),
        sa.Column('tipo_integracao', sa.String(
            length=1), nullable=True),
        sa.Column('outra_forma', sa.String(
            length=60), nullable=True),
        sa.Column('a_prazo', sa.Boolean(),
                  server_default='false', nullable=False),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.ForeignKeyConstraint(['instituicao_pagamento_id'], [
            'instituicao_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'codigo',
            name='forma_pagamento_domain_id_tarefa_id_codigo_uk'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'nome',
            name='forma_pagamento_domain_id_tarefa_id_nome_uk')
    )
    op.create_table(
        'condicao_pagamento_parcela',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('condicao_pagamento_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('forma_pagamento_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('numero', sa.Numeric(
            precision=3), nullable=False),
        sa.Column('dias_prazo', sa.Numeric(
            precision=3), nullable=False),
        sa.ForeignKeyConstraint(['condicao_pagamento_id'], [
            'condicao_pagamento.id'], ),
        sa.ForeignKeyConstraint(['forma_pagamento_id'], [
            'forma_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_pagar_evento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_pagar_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('status', sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                                    name='contapagarstatus'),
                  server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conta_pagar_id'], [
            'conta_pagar.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_pagar_parcela',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_pagar_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('forma_pagto_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('numero', sa.Numeric(
            precision=3), nullable=False),
        sa.Column('numero_doc', sa.String(
            length=50), nullable=True),
        sa.Column('vencimento', sa.Date(), nullable=False),
        sa.Column('valor', sa.Numeric(
            precision=17, scale=4), nullable=False),
        sa.Column('valor_inicial', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('status',
                  sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                          name='contapagarparcelastatus'),
                  server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.String(
            length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('a_prazo', sa.Boolean(),
                  server_default='false', nullable=False),
        sa.Column('desconto', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('observacao', sa.String(
            length=100), nullable=True),
        sa.ForeignKeyConstraint(['conta_pagar_id'], [
            'conta_pagar.id'], ),
        sa.ForeignKeyConstraint(['forma_pagto_id'], [
            'forma_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'conta_pagar_id', 'numero',
            name='conta_pagar_parcela_conta_pagar_id_numero_uk')
    )
    op.create_table(
        'conta_pagar_pagto',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('forma_pagto_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('conta_pagar_parcela_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('data_hora', sa.DateTime(), nullable=False),
        sa.Column('valor', sa.Numeric(
            precision=17, scale=4), nullable=False),
        sa.ForeignKeyConstraint(['conta_pagar_parcela_id'], [
            'conta_pagar_parcela.id'], ),
        sa.ForeignKeyConstraint(['forma_pagto_id'], [
            'forma_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_pagar_parcela_evento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_pagar_parcela_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('status', sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                                    name='contapagarparcelastatus'),
                  server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('observacao', sa.String(
            length=100), nullable=True),
        sa.ForeignKeyConstraint(['conta_pagar_parcela_id'], [
            'conta_pagar_parcela.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_receber',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('portador_id', sa.CHAR(length=32), nullable=True),
        sa.Column('centro_resultado_id', sa.CHAR(
            length=32), nullable=True),
        sa.Column('natureza_financeira_id',
                  sa.CHAR(length=32), nullable=True),
        sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
        sa.Column('conta_energia_id', sa.CHAR(
            length=32), nullable=True),
        sa.Column('numero', sa.Numeric(
            precision=10), nullable=False),
        sa.Column('numero_doc', sa.String(
            length=50), nullable=True),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('observacao', sa.String(
            length=500), nullable=True),
        sa.Column('status', sa.Enum(
            'CRIADA', 'CANCELADA', 'BAIXADA',
            name='conta_receber_status'), server_default='CRIADA',
            nullable=False),
        sa.Column('status_por', sa.String(
            length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('valor_juros', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('valor_multa', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('valor_mora', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('origem', sa.String(length=5), nullable=False),
        sa.Column('serie', sa.Numeric(precision=10), nullable=True),
        sa.ForeignKeyConstraint(['centro_resultado_id'], [
            'centro_resultado.id'], ),
        sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
        sa.ForeignKeyConstraint(['conta_energia_id'], [
            'conta_energia.id'], ),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.ForeignKeyConstraint(['natureza_financeira_id'], [
            'natureza_financeira.id'], ),
        sa.ForeignKeyConstraint(['portador_id'], ['portador.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'conta_energia_id',
            name='conta_receber_domain_id_tarefa_id_conta_energia_id_uk'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'numero',
            name='conta_receber_domain_id_tarefa_id_numero_uk'),
        sa.UniqueConstraint(
            'domain_id', 'tarefa_id', 'numero_doc',
            name='conta_receber_domain_id_tarefa_id_numero_doc_uk')
    )
    op.create_index('ix_conta_receber_numero', 'conta_receber',
                    ['domain_id', 'numero'], unique=True)
    op.create_table(
        'conta_receber_evento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_receber_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('status', sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                                    name='conta_receber_status'),
                  server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['conta_receber_id'], [
            'conta_receber.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_receber_parcela',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_receber_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('forma_pagto_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('numero', sa.Numeric(
            precision=3), nullable=False),
        sa.Column('vencimento', sa.Date(), nullable=False),
        sa.Column('valor', sa.Numeric(
            precision=17, scale=4), nullable=False),
        sa.Column('status', sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                                    name='conta_receber_parcela_status'),
                  server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.String(
            length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('a_prazo', sa.Boolean(), nullable=True),
        sa.Column('desconto', sa.Numeric(precision=17, scale=4),
                  server_default='0', nullable=False),
        sa.Column('observacao', sa.String(
            length=100), nullable=True),
        sa.Column('baixada_com_juros', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['conta_receber_id'], [
            'conta_receber.id'], ),
        sa.ForeignKeyConstraint(['forma_pagto_id'], [
            'forma_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('conta_receber_id', 'numero',
                            name='conta_receber_parcela_domain_id_numero_uk')
    )
    op.create_table(
        'conta_receber_pagto',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('forma_pagto_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('conta_receber_parcela_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('data_hora', sa.DateTime(), nullable=False),
        sa.Column('valor', sa.Numeric(
            precision=17, scale=4), nullable=False),
        sa.ForeignKeyConstraint(['conta_receber_parcela_id'], [
            'conta_receber_parcela.id'], ),
        sa.ForeignKeyConstraint(['forma_pagto_id'], [
            'forma_pagamento.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'conta_receber_parcela_evento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('conta_receber_parcela_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('status', sa.Enum('CRIADA', 'CANCELADA', 'BAIXADA',
                                    name='conta_receber_parcela_status'),
                  server_default='CRIADA', nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('observacao', sa.String(
            length=100), nullable=True),
        sa.ForeignKeyConstraint(['conta_receber_parcela_id'], [
            'conta_receber_parcela.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta_receber_parcela_evento')
    op.drop_table('conta_receber_pagto')
    op.drop_table('conta_receber_parcela')
    op.drop_table('conta_receber_evento')
    op.drop_index('ix_conta_receber_numero', table_name='conta_receber')
    op.drop_table('conta_receber')
    op.drop_table('conta_pagar_parcela_evento')
    op.drop_table('conta_pagar_pagto')
    op.drop_table('conta_pagar_parcela')
    op.drop_table('conta_pagar_evento')
    op.drop_table('condicao_pagamento_parcela')
    op.drop_table('forma_pagamento')
    op.drop_index('ix_conta_pagar_numero', table_name='conta_pagar')
    op.drop_table('conta_pagar')
    op.drop_table('portador')
    op.drop_table('pix')
    op.drop_table('natureza_financeira')
    op.drop_table('instituicao_pagamento')
    op.drop_table('condicao_pagamento')
    op.drop_table('centro_resultado')
    # ### end Alembic commands ###
