"""24.08.21 - add paises

Revision ID: 353827c93ebe
Revises: 58345b304bf6
Create Date: 2024-08-21 19:47:03.442022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353827c93ebe'
down_revision = '58345b304bf6'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    session = create_session(op)
    session.execute("""
        INSERT INTO public.pais
        (id, active, created_at, created_by, updated_at, updated_by, tag, codigo, nome)
        VALUES
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 132, 'AFEGANISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7560, 'AFRICA DO SUL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 175, 'ALBANIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 230, 'ALEMANHA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 370, 'ANDORRA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 400, 'ANGOLA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 418, 'ANGUILLA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 434, 'ANTIGUA E BARBUDA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 531, 'ARABIA SAUDITA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 590, 'ARGELIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 639, 'ARGENTINA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 647, 'ARMENIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 655, 'ARUBA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 698, 'AUSTRALIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 728, 'AUSTRIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 736, 'AZERBAIDJAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 779, 'BAHAMAS, ILHAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 817, 'BANGLADESH'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 833, 'BARBADOS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 809, 'BAREIN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 850, 'BELARUS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 876, 'BELGICA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 884, 'BELIZE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2291, 'BENIN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 906, 'BERMUDAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 973, 'BOLIVIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 990, 'BONAIRE, SAINT EUSTATIUS E SABA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 981, 'BOSNIA-HERZEGOVINA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1015, 'BOTSUANA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1098, 'BOUVET, ILHA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1058, 'BRASIL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1082, 'BRUNEI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1112, 'BULGARIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 310, 'BURKINA FASO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1155, 'BURUNDI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1198, 'BUTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1279, 'CABO VERDE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1457, 'CAMAROES'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1414, 'CAMBOJA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1490, 'CANADA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1546, 'CATAR'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1376, 'CAYMAN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1538, 'CAZAQUISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7889, 'CHADE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1589, 'CHILE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1600, 'CHINA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1635, 'CHIPRE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5118, 'CHRISTMAS, ILHA (NAVIDAD)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7412, 'CINGAPURA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1651, 'COCOS (KEELINGS)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1694, 'COLOMBIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1732, 'COMORES'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1775, 'CONGO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1830, 'COOK'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1872, 'COREIA DO NORTE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1902, 'COREIA DO SUL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1937, 'COSTA DO MARFIM'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1961, 'COSTA RICA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1953, 'CROACIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1996, 'CUBA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2003, 'CURACAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2321, 'DINAMARCA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7838, 'DJIBUTI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2356, 'DOMINICA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2402, 'EGITO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6874, 'EL SALVADOR'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2445, 'EMIRADOS ARABES UNIDOS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2399, 'EQUADOR'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2437, 'ERITREIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2470, 'ESLOVAQUIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2461, 'ESLOVENIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2453, 'ESPANHA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2496, 'ESTADOS UNIDOS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2518, 'ESTONIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7544, 'ESWATINI (ANTIGA SUAZILANDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2534, 'ETIOPIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2550, 'FALKLAND (MALVINAS)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2593, 'FAROE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8702, 'FIJI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2674, 'FILIPINAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2712, 'FINLANDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2755, 'FRANCA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2810, 'GABAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2852, 'GAMBIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2895, 'GANA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2917, 'GEORGIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2933, 'GIBRALTAR'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 2976, 'GRANADA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3018, 'GRECIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3050, 'GROENLANDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3093, 'GUADALUPE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3131, 'GUAM'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3174, 'GUATEMALA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1504, 'GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3379, 'GUIANA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3255, 'GUIANA FRANCESA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3298, 'GUINE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3344, 'GUINE-BISSAU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3310, 'GUINE-EQUATORIAL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3417, 'HAITI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5738, 'HOLANDA (PAISES BAIXOS)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3450, 'HONDURAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3514, 'HONG KONG'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3557, 'HUNGRIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3573, 'IEMEN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3611, 'INDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3654, 'INDONESIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3727, 'IRA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3697, 'IRAQUE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3751, 'IRLANDA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3794, 'ISLANDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3832, 'ISRAEL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3867, 'ITALIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3913, 'JAMAICA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3999, 'JAPAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1508, 'JERSEY, ILHA DO CANAL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3964, 'JOHNSTON'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4030, 'JORDANIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4111, 'KIRIBATI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1988, 'KUWEIT (ou Coveite)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4200, 'LAOS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4260, 'LESOTO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4278, 'LETONIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4316, 'LIBANO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4340, 'LIBERIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4383, 'LIBIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4405, 'LIECHTENSTEIN'),
        --    (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4421, 'LITUANIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4456, 'LUXEMBURGO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4472, 'MACAU'),
        --    (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4421, 'MACEDONIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4502, 'MADAGASCAR'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4553, 'MALASIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4588, 'MALAVI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4618, 'MALDIVAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4642, 'MALI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4677, 'MALTA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 3595, 'MAN, ILHA DE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4723, 'MARIANAS DO NORTE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4740, 'MARROCOS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4766, 'MARSHALL, ILHAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4774, 'MARTINICA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4855, 'MAURICIO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4880, 'MAURITANIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4936, 'MEXICO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 930, 'MIANMAR'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4995, 'MICRONESIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5053, 'MOCAMBIQUE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4944, 'MOLDAVIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4952, 'MONACO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4979, 'MONGOLIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 4985, 'MONTENEGRO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5010, 'MONTSERRAT'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5070, 'NAMIBIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5088, 'NAURU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5177, 'NEPAL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5215, 'NICARAGUA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5258, 'NIGER'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5282, 'NIGERIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5312, 'NIUE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5355, 'NORFOLK, ILHA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5380, 'NORUEGA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5428, 'NOVA CALEDONIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5487, 'NOVA ZELANDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5568, 'OMA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5665, 'PACIFICO, ILHAS DO (POSSESSAO DOS EUA)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5754, 'PALAU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5780, 'PALESTINA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5800, 'PANAMA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5452, 'PAPUA NOVA GUINE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5762, 'PAQUISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5860, 'PARAGUAI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5894, 'PERU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5932, 'PITCAIRN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5991, 'POLINESIA FRANCESA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6033, 'POLONIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6114, 'PORTO RICO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6076, 'PORTUGAL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6238, 'QUENIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6254, 'QUIRGUISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6289, 'REINO UNIDO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6408, 'REPUBLICA CENTRO-AFRICANA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8885, 'REPUBLICA DEMOCRATICA DO CONGO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6475, 'REPUBLICA DOMINICANA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7919, 'REPUBLICA TCHECA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6602, 'REUNIAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6700, 'ROMENIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6750, 'RUANDA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6769, 'RUSSIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6858, 'SAARA OCIDENTAL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6777, 'SALOMAO, ILHAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6904, 'SAMOA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6912, 'SAMOA AMERICANA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6971, 'SAN MARINO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7102, 'SANTA HELENA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7153, 'SANTA LUCIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6955, 'SAO CRISTOVAO E NEVES'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6980, 'SAO MARTINHO, ILHA DE (PARTE FRANCESA)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6998, 'SAO MARTINHO, ILHA DE (PARTE HOLANDESA)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7005, 'SAO PEDRO E MIQUELON'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7200, 'SAO TOME E PRINCIPE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7056, 'SAO VICENTE E GRANADINAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7315, 'SEICHELES'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7285, 'SENEGAL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7358, 'SERRA LEOA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7370, 'SERVIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7447, 'SIRIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7480, 'SOMALIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7501, 'SRI LANKA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7595, 'SUDAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7600, 'SUDÃO DO SUL'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7641, 'SUECIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7676, 'SUICA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7706, 'SURINAME'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7552, 'SVALBARD E JAN MAYEN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7722, 'TADJIQUISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7765, 'TAILANDIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 1619, 'TAIWAN'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7803, 'TANZANIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7820, 'TERRITORIO BRITANICO OCEANO INDICO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 7951, 'TIMOR LESTE'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8001, 'TOGO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8109, 'TONGA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8052, 'TOQUELAU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8150, 'TRINIDAD E TOBAGO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8206, 'TUNISIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8230, 'TURCAS E CAICOS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8249, 'TURCOMENISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8273, 'TURQUIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8281, 'TUVALU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8311, 'UCRANIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8338, 'UGANDA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8451, 'URUGUAI'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8478, 'UZBEQUISTAO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 5517, 'VANUATU'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8486, 'VATICANO'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8508, 'VENEZUELA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8583, 'VIETNA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8630, 'VIRGENS, ILHAS (BRITANICAS)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8664, 'VIRGENS, ILHAS (EUA)'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8753, 'WALLIS E FUTUNA, ILHAS'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 8907, 'ZAMBIA'),
            (md5((random())::text), true, now(), null, null, null, '#ADD_VIA_SCRIPT', 6653, 'ZIMBABUE');
        """)  # noqa


def downgrade():
    session = create_session(op)
    session.execute("""
    DELETE FROM pais WHERE 1=1;
    """)
