"""25.04.13 - Add formas_pagamento em ContaEnergia

Revision ID: 37fe72ceb1b4
Revises: f0912074ec63
Create Date: 2025-04-13 17:23:47.207199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fe72ceb1b4'
down_revision = 'f0912074ec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conta_energia_forma_pagamento',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('conta_energia_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('forma_pagamento_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('dias_prazo', sa.Numeric(
                        precision=3), nullable=False),
                    sa.Column('valor', sa.Numeric(
                        precision=15, scale=3), nullable=False),
                    sa.Column('a_prazo', sa.Boolean(), nullable=False),
                    sa.Column('numero', sa.Numeric(
                        precision=3), nullable=False),
                    sa.ForeignKeyConstraint(['conta_energia_id'], [
                                            'conta_energia.id'], ),
                    sa.ForeignKeyConstraint(['forma_pagamento_id'], [
                        'forma_pagamento.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta_energia_forma_pagamento')
    # ### end Alembic commands ###
