"""24.10.10 - atualizacao tabela conta_energia

Revision ID: 3f51bd31b116
Revises: 45cc297a67e3
Create Date: 2024-10-03 08:52:47.532094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f51bd31b116'
down_revision = '45cc297a67e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta_energia', sa.Column(
        'estabelecimento_id', sa.CHAR(length=32), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'ref_mes_ano', sa.String(length=7), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'vencimento', sa.DateTime(), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'dt_leitura_anterior', sa.DateTime(), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'dt_leitura_atual', sa.DateTime(), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'n_dias', sa.Numeric(precision=3), nullable=False))
    op.add_column('conta_energia', sa.Column('leitura_anterior',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('leitura_atual',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('diferenca_leituras',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('preco_referencia',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'iluminacao_publica_media', sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('total_cosern',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('desconto_nominal_valor',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'desconto_nominal_porcentagem', sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('desconto_efetivo_valor',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'desconto_efetivo_porcentagem', sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column('total_tarefa',
                  sa.Numeric(precision=17, scale=2), nullable=False))
    op.add_column('conta_energia', sa.Column(
        'cat', sa.Numeric(precision=17, scale=2), nullable=True))
    op.alter_column('conta_energia', 'documento_id',
                    existing_type=sa.CHAR(length=32),
                    nullable=False)
    op.create_unique_constraint(
        'conta_energia_domain_id_estabelecimento_id_ref_mes_ano_uk',
        'conta_energia',
        ['domain_id', 'estabelecimento_id', 'ref_mes_ano'])
    op.create_foreign_key(
        'conta_energia_estabelecimento_id_fkey',
        'conta_energia', 'estabelecimento',
        ['estabelecimento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conta_energia_estabelecimento_id_fkey',
                       'conta_energia', type_='foreignkey')
    op.drop_constraint(
        'conta_energia_domain_id_estabelecimento_id_ref_mes_ano_uk',
        'conta_energia', type_='unique')
    op.alter_column('conta_energia', 'documento_id',
                    existing_type=sa.CHAR(length=32),
                    nullable=True)
    op.drop_column('conta_energia', 'cat')
    op.drop_column('conta_energia', 'total_tarefa')
    op.drop_column('conta_energia', 'desconto_efetivo_porcentagem')
    op.drop_column('conta_energia', 'desconto_efetivo_valor')
    op.drop_column('conta_energia', 'desconto_nominal_porcentagem')
    op.drop_column('conta_energia', 'desconto_nominal_valor')
    op.drop_column('conta_energia', 'total_cosern')
    op.drop_column('conta_energia', 'iluminacao_publica_media')
    op.drop_column('conta_energia', 'preco_referencia')
    op.drop_column('conta_energia', 'diferenca_leituras')
    op.drop_column('conta_energia', 'leitura_atual')
    op.drop_column('conta_energia', 'leitura_anterior')
    op.drop_column('conta_energia', 'n_dias')
    op.drop_column('conta_energia', 'dt_leitura_atual')
    op.drop_column('conta_energia', 'dt_leitura_anterior')
    op.drop_column('conta_energia', 'vencimento')
    op.drop_column('conta_energia', 'ref_mes_ano')
    op.drop_column('conta_energia', 'estabelecimento_id')
    # ### end Alembic commands ###
