"""24.09.10 - nome_razao_social passa a ser possivelmente nulo em parceiro

Revision ID: 45cc297a67e3
Revises: 61cae89c60ff
Create Date: 2024-09-10 18:52:56.435909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cc297a67e3'
down_revision = '61cae89c60ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parceiro', 'cpf_cnpj',
                    existing_type=sa.CHAR(length=14),
                    nullable=False)
    op.alter_column('parceiro', 'nome_razao_social',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parceiro', 'nome_razao_social',
                    existing_type=sa.VARCHAR(length=60),
                    nullable=False)
    op.alter_column('parceiro', 'cpf_cnpj',
                    existing_type=sa.CHAR(length=14),
                    nullable=True)
    # ### end Alembic commands ###
