"""25.02.22 - Adiciona movimentacao_financeira, numero em conta_energia,
e taxa_juros_padrao em cliente

Revision ID: 4a9b0097f627
Revises: 1ca349b9e2b0
Create Date: 2025-02-22 13:36:39.362883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9b0097f627'
down_revision = '1ca349b9e2b0'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    session = create_session(op)
    session.execute("""
        DELETE FROM conta_receber_pagto;
        DELETE FROM conta_receber_parcela_evento;
        DELETE FROM conta_receber_parcela;
        DELETE FROM conta_receber_evento;
        DELETE FROM conta_receber;
        DELETE FROM conta_energia_evento;
        DELETE FROM conta_energia;

        -- atualiza settings dos tarefaes com as regras default
        UPDATE tarefa
        SET settings='{"regras": {"controle": {"conta_receber": {"contas_atraso": "UNKNOWN","taxa_juros_mes": 0,"dias_tolerancia_juros": 0, "gerar_auto_conta_energia": false}},"config_financeira": {"operacoes": [],"operacao_padrao_receber": null,"operacao_padrao_pagar": null}}}'
        WHERE settings='{}';
    """)  # noqa
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'movimentacao_financeira',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
        sa.Column('tarefa_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('portador_id', sa.CHAR(
            length=32), nullable=False),
        sa.Column('conta_receber_pagto_id',
                  sa.CHAR(length=32), nullable=True),
        sa.Column('conta_pagar_pagto_id', sa.CHAR(
            length=32), nullable=True),
        sa.Column('data_movimento', sa.DateTime(), nullable=False),
        sa.Column('valor', sa.Numeric(
            precision=17, scale=4), nullable=False),
        sa.Column('observacao', sa.String(
            length=200), nullable=False),
        sa.Column('conciliado_dh', sa.DateTime(), nullable=True),
        sa.Column('conciliado_por', sa.CHAR(
            length=32), nullable=True),
        sa.Column('numero', sa.Numeric(
            precision=10), nullable=False),
        sa.Column('origem_id', sa.CHAR(length=32), nullable=True),
        sa.Column('status', sa.Enum('CRIADO', 'CANCELADO',
                                    name='movimentacaofinanceirastatus'),
                  nullable=True),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(['conciliado_por'], ['user.id'], ),
        sa.ForeignKeyConstraint(['conta_pagar_pagto_id'], [
            'conta_pagar_pagto.id'], ),
        sa.ForeignKeyConstraint(['conta_receber_pagto_id'], [
            'conta_receber_pagto.id'], ),
        sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
        sa.ForeignKeyConstraint(
            ['tarefa_id'], ['tarefa.id'], ),
        sa.ForeignKeyConstraint(
            ['origem_id'], ['movimentacao_financeira.id'], ),
        sa.ForeignKeyConstraint(['portador_id'], ['portador.id'], ),
        sa.ForeignKeyConstraint(['status_por'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('domain_id', 'numero',
                            name='movimentacao_financeira_domain_id_numero_uk')
    )
    op.create_index('ix_movimentacao_financeira_numero',
                    'movimentacao_financeira',
                    ['domain_id', 'numero'], unique=True)
    op.create_table(
        'movimentacao_financeira_evento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.CHAR(length=32), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
        sa.Column('tag', sa.String(length=1000), nullable=True),
        sa.Column('movimentacao_financeira_id',
                  sa.CHAR(length=32), nullable=False),
        sa.Column('status', sa.Enum('CRIADO', 'CANCELADO',
                                    name='movimentacaofinanceirastatus'),
                  nullable=False),
        sa.Column('status_dh', sa.DateTime(), nullable=False),
        sa.Column('status_por', sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(['movimentacao_financeira_id'], [
            'movimentacao_financeira.id'], ),
        sa.ForeignKeyConstraint(['status_por'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cliente', sa.Column('taxa_juros_padrao',
                  sa.Numeric(precision=23, scale=10), nullable=True))
    op.add_column('conta_energia', sa.Column(
        'numero', sa.Numeric(precision=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_energia', 'numero')
    op.drop_column('cliente', 'taxa_juros_padrao')
    op.drop_table('movimentacao_financeira_evento')
    op.drop_index('ix_movimentacao_financeira_numero',
                  table_name='movimentacao_financeira')
    op.drop_table('movimentacao_financeira')
    # ### end Alembic commands ###
