"""25.01.17 - Alteracao calulo da conta de energia

Revision ID: 4ceebba15ada
Revises: 89ce47c774b3
Create Date: 2025-01-17 18:17:56.117622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4ceebba15ada'
down_revision = '89ce47c774b3'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    session = create_session(op)
    session.execute(
        '''
        ALTER TABLE cliente_estabelecimento ALTER COLUMN tipo_calculo
        TYPE VARCHAR(255);
        ALTER TABLE conta_energia ALTER COLUMN tipo_calculo TYPE VARCHAR(255);

        DROP TYPE IF EXISTS tipo_calculo;

        UPDATE cliente_estabelecimento
        SET tipo_calculo='DESCONTO_EFETIVO'
        WHERE tipo_calculo='DESCONTO_NOMINAL';

        UPDATE cliente_estabelecimento
        SET tipo_calculo='DESCONTO_EFETIVO'
        WHERE tipo_calculo='DESCONTO_NOMINAL';

        CREATE TYPE tipo_calculo
        AS ENUM ('DESCONTO_EFETIVO', 'CUSTO_POR_QUILO');

        ALTER TABLE cliente_estabelecimento ALTER COLUMN tipo_calculo
        TYPE tipo_calculo USING (tipo_calculo::tipo_calculo);
        '''
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parceiro')
    op.add_column('cliente_estabelecimento',
                  sa.Column('desconto_efetivo', sa.Numeric(
                      precision=23, scale=10), server_default='0.0',
                      nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'iluminacao_porcentagem', sa.Boolean(), server_default='false',
        nullable=False))
    op.drop_column('cliente_estabelecimento', 'desconto_nominal')
    op.add_column('conta_energia', sa.Column('iluminacao_porcentagem',
                  sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('tarefa', 'cpf_cnpj',
                    existing_type=sa.CHAR(length=14),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tarefa', 'cpf_cnpj',
                    existing_type=sa.CHAR(length=14),
                    nullable=True)
    op.drop_column('conta_energia', 'iluminacao_porcentagem')
    op.add_column(
        'cliente_estabelecimento',
        sa.Column('desconto_nominal',
                  sa.NUMERIC(
                      precision=23, scale=10), server_default=sa.text('0.0'),
                  autoincrement=False, nullable=False))
    op.drop_column('cliente_estabelecimento', 'iluminacao_porcentagem')
    op.drop_column('cliente_estabelecimento', 'desconto_efetivo')
    op.create_table('parceiro',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('tag', sa.VARCHAR(length=1000),
                              autoincrement=False, nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('cpf_cnpj', sa.CHAR(length=14),
                              autoincrement=False, nullable=False),
                    sa.Column('doc_estrangeiro', sa.CHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.Column('rg_insc_est', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.Column('nome_razao_social', sa.VARCHAR(length=60),
                              autoincrement=False, nullable=True),
                    sa.Column('apelido_nome_fantasia', sa.VARCHAR(
                        length=60), autoincrement=False, nullable=True),
                    sa.Column('observacao', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('data_nascimento', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('user_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['domain_id'], ['domain.id'],
                        name='parceiro_domain_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='parceiro_pkey')
                    )
    # ### end Alembic commands ###

    session = create_session(op)
    session.execute(
        '''
        ALTER TABLE cliente_estabelecimento ALTER COLUMN tipo_calculo
        TYPE VARCHAR(255);
        ALTER TABLE conta_energia ALTER COLUMN tipo_calculo TYPE VARCHAR(255);

        DROP TYPE IF EXISTS tipo_calculo;

        UPDATE cliente_estabelecimento
        SET tipo_calculo='DESCONTO_NOMINAL'
        WHERE tipo_calculo='DESCONTO_EFETIVO';

        UPDATE cliente_estabelecimento
        SET tipo_calculo='DESCONTO_NOMINAL'
        WHERE tipo_calculo='DESCONTO_EFETIVO';

        CREATE TYPE tipo_calculo
        AS ENUM ('DESCONTO_NOMINAL', 'CUSTO_POR_QUILO');

        ALTER TABLE cliente_estabelecimento ALTER COLUMN tipo_calculo
        TYPE tipo_calculo USING (tipo_calculo::tipo_calculo);
        '''
    )
