"""24.10.09 - att cliente_estabelecimento e conta_energia

Revision ID: 5005e823fd8d
Revises: 3f51bd31b116
Create Date: 2024-10-09 19:59:17.335099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5005e823fd8d'
down_revision = '3f51bd31b116'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    session = create_session(op)
    session.execute("""
        CREATE TYPE tipo_calculo AS ENUM (
            'DESCONTO_NOMINAL',
            'CUSTO_POR_QUILO');
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cliente_estabelecimento',
        sa.Column('iluminacao_publica_media', sa.Numeric(
            precision=17, scale=4), nullable=False, server_default='0.0'))
    op.add_column(
        'cliente_estabelecimento', sa.Column('custo_medio_energia', sa.Numeric(
            precision=17, scale=4), nullable=False, server_default='0.0'))
    op.add_column(
        'cliente_estabelecimento', sa.Column('desconto_nominal', sa.Numeric(
            precision=17, scale=4), nullable=False, server_default='0.0'))
    op.add_column('conta_energia', sa.Column('tipo_calculo', sa.Enum(
        'DESCONTO_NOMINAL', 'CUSTO_POR_QUILO', name='tipo_calculo'),
        nullable=False))
    op.add_column(
        'conta_energia', sa.Column('custo_por_quilo', sa.Numeric(
            precision=17, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_energia', 'tipo_calculo')
    op.drop_column('conta_energia', 'custo_por_quilo')
    op.drop_column('cliente_estabelecimento', 'desconto_nominal')
    op.drop_column('cliente_estabelecimento', 'custo_medio_energia')
    op.drop_column('cliente_estabelecimento', 'iluminacao_publica_media')
    # ### end Alembic commands ###

    session = create_session(op)
    session.execute("""
        DROP TYPE IF EXISTS tipo_calculo;
        """)
