"""25.03.15 - Adiciona historico_reuso

Revision ID: 55b4bf535007
Revises: 4a9b0097f627
Create Date: 2025-03-15 18:29:42.431946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b4bf535007'
down_revision = '4a9b0097f627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historico_reuso',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('entidade_nome', sa.String(
                        length=60), nullable=False),
                    sa.Column('entidade_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('payload', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_reuso')
    # ### end Alembic commands ###
