"""24.08.21 - entidades pós reunião

Revision ID: 58345b304bf6
Revises: e8e62c818a50
Create Date: 2024-08-21 19:27:05.723477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58345b304bf6'
down_revision = 'e8e62c818a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('codigo', sa.Numeric(
                        precision=10), nullable=False),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(['id'], ['parceiro.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('domain_id', 'codigo',
                                        name='tarefa_domain_id_codigo_uk')
                    )
    op.create_table('cliente_tarefa',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('tarefa_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('observacao', sa.String(
                        length=100), nullable=True),
                    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tarefa_id'], ['tarefa.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'domain_id', 'cliente_id', 'tarefa_id',
                        name='cliente_domain_id_cliente_id_tarefa_id_uk')
                    )
    op.create_table('estabelecimento',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('municipio_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('pais_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('codigo_cliente', sa.String(
                        length=10), nullable=False),
                    sa.Column('logradouro', sa.String(
                        length=255), nullable=False),
                    sa.Column('numero', sa.String(length=60), nullable=False),
                    sa.Column('bairro', sa.String(length=60), nullable=False),
                    sa.Column('cep', sa.String(length=8), nullable=False),
                    sa.Column('complemento', sa.String(
                        length=60), nullable=True),
                    sa.Column('ponto_referencia', sa.String(
                        length=512), nullable=True),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(
                        ['municipio_id'], ['municipio.id'], ),
                    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'domain_id', 'codigo_cliente',
                        name='estabelecimento_domain_id_codigo_cliente_uk')
                    )
    op.create_table('cliente_estabelecimento',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('tarefa_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('estabelecimento_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('custo_por_quilo', sa.Numeric(
                        precision=17, scale=4), nullable=False),
                    sa.Column('descricao', sa.String(
                        length=100), nullable=True),
                    sa.Column('complemento', sa.String(
                        length=100), nullable=True),
                    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.ForeignKeyConstraint(['estabelecimento_id'], [
                        'estabelecimento.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tarefa_id'], ['tarefa.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint(
                        'domain_id', 'cliente_id', 'tarefa_id',
                        'estabelecimento_id',
                        name='cliente_dom_id_cli_id_for_id_est_id_uk')
                    )
    op.drop_column('cliente', 'data_nascimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('data_nascimento',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_table('cliente_estabelecimento')
    op.drop_table('estabelecimento')
    op.drop_table('cliente_tarefa')
    op.drop_table('tarefa')
    # ### end Alembic commands ###
