"""25.03.26 - add campo valor_multa_padrao em cliente e data_pagamento em
conta_energia

Revision ID: 58c39ab10930
Revises: 9d0da325591c
Create Date: 2025-03-26 22:43:16.237222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c39ab10930'
down_revision = '9d0da325591c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('valor_multa_padrao',
                  sa.Numeric(precision=23, scale=10), nullable=True))
    op.add_column('conta_energia', sa.Column(
        'data_pagamento', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_energia', 'data_pagamento')
    op.drop_column('cliente', 'valor_multa_padrao')
    # ### end Alembic commands ###
