"""25.04.24 - add coluna portador_id em conta_receber_pagto

Revision ID: 755ba8ca5078
Revises: 2bfe12990830
Create Date: 2025-04-24 06:48:46.211470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755ba8ca5078'
down_revision = '2bfe12990830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta_receber_pagto', sa.Column(
        'portador_id', sa.CHAR(length=32), nullable=False))
    op.create_foreign_key(
        'conta_receber_pagto_portador_id_fkey',
        'conta_receber_pagto', 'portador',
        ['portador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conta_receber_pagto_portador_id_fkey',
                       'conta_receber_pagto', type_='foreignkey')
    op.drop_column('conta_receber_pagto', 'portador_id')
    # ### end Alembic commands ###
