"""24.10.24 - corrige campos de cliente_estabelecimento

Revision ID: 799c09cdadab
Revises: e3d42760c444
Create Date: 2024-10-24 19:20:05.802948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '799c09cdadab'
down_revision = 'e3d42760c444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente_estabelecimento', sa.Column(
        'municipio_id', sa.CHAR(length=32), nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'pais_id', sa.CHAR(length=32), nullable=True))
    op.add_column('cliente_estabelecimento', sa.Column(
        'codigo_cliente', sa.String(length=10), nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'logradouro', sa.String(length=255), nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'numero', sa.String(length=60), nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'bairro', sa.String(length=60), nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'cep', sa.String(length=8), nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'ponto_referencia', sa.String(length=512), nullable=True))
    op.add_column('cliente_estabelecimento', sa.Column('tipo_calculo', sa.Enum(
        'DESCONTO_NOMINAL', 'CUSTO_POR_QUILO', name='tipo_calculo'),
        nullable=False))
    op.alter_column('cliente_estabelecimento', 'descricao',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=False)
    op.drop_constraint('cliente_dom_id_cli_id_for_id_est_id_uk',
                       'cliente_estabelecimento', type_='unique')
    op.create_unique_constraint(
        'cliente_dom_id_cli_id_for_id_cod_cli_uk', 'cliente_estabelecimento',
        ['domain_id', 'cliente_id', 'tarefa_id', 'codigo_cliente'])
    op.drop_constraint('cliente_estabelecimento_estabelecimento_id_fkey',
                       'cliente_estabelecimento', type_='foreignkey')
    op.create_foreign_key('cliente_estabelecimento_municipio_id_fkey',
                          'cliente_estabelecimento',
                          'municipio', ['municipio_id'], ['id'])
    op.create_foreign_key(
        'cliente_estabelecimento_pais_id_fkey', 'cliente_estabelecimento',
        'pais', ['pais_id'], ['id'])
    op.drop_column('cliente_estabelecimento', 'nome')
    op.drop_column('cliente_estabelecimento', 'estabelecimento_id')
    op.add_column('conta_energia', sa.Column(
        'cliente_estabelecimento_id', sa.CHAR(length=32), nullable=False))
    op.drop_constraint(
        'conta_energia_domain_id_estabelecimento_id_ref_mes_ano_uk',
        'conta_energia', type_='unique')
    op.create_unique_constraint(
        'conta_energia_domain_id_cli_est_id_ref_mes_ano_uk', 'conta_energia', [
            'domain_id', 'cliente_estabelecimento_id', 'ref_mes_ano'])
    op.drop_constraint('conta_energia_estabelecimento_id_fkey',
                       'conta_energia', type_='foreignkey')
    op.create_foreign_key('conta_energia_cliente_estabelecimento_id_fkey',
                          'conta_energia', 'cliente_estabelecimento',
                          ['cliente_estabelecimento_id'], ['id'])
    op.drop_column('conta_energia', 'estabelecimento_id')
    op.drop_table('estabelecimento')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conta_energia', sa.Column('estabelecimento_id',
                  sa.CHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint('conta_energia_cliente_estabelecimento_id_fkey',
                       'conta_energia', type_='foreignkey')
    op.create_foreign_key('conta_energia_estabelecimento_id_fkey',
                          'conta_energia', 'estabelecimento',
                          ['estabelecimento_id'], ['id'])
    op.drop_constraint(
        'conta_energia_domain_id_cli_est_id_ref_mes_ano_uk', 'conta_energia',
        type_='unique')
    op.create_unique_constraint(
        'conta_energia_domain_id_estabelecimento_id_ref_mes_ano_uk',
        'conta_energia', ['domain_id', 'estabelecimento_id', 'ref_mes_ano'])
    op.drop_column('conta_energia', 'cliente_estabelecimento_id')
    op.add_column('cliente_estabelecimento', sa.Column(
        'estabelecimento_id', sa.CHAR(length=32), autoincrement=False,
        nullable=False))
    op.add_column('cliente_estabelecimento', sa.Column(
        'nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint('cliente_estabelecimento_municipio_id_fkey',
                       'cliente_estabelecimento', type_='foreignkey')
    op.drop_constraint('cliente_estabelecimento_pais_id_fkey',
                       'cliente_estabelecimento', type_='foreignkey')
    op.create_foreign_key('cliente_estabelecimento_estabelecimento_id_fkey',
                          'cliente_estabelecimento', 'estabelecimento',
                          ['estabelecimento_id'], ['id'])
    op.drop_constraint('cliente_dom_id_cli_id_for_id_cod_cli_uk',
                       'cliente_estabelecimento', type_='unique')

    op.create_unique_constraint(
        'cliente_dom_id_cli_id_for_id_est_id_uk', 'cliente_estabelecimento', [
            'domain_id', 'cliente_id', 'tarefa_id', 'estabelecimento_id'])
    op.alter_column('cliente_estabelecimento', 'descricao',
                    existing_type=sa.VARCHAR(length=100),
                    nullable=True)
    op.drop_column('cliente_estabelecimento', 'tipo_calculo')
    op.drop_column('cliente_estabelecimento', 'ponto_referencia')
    op.drop_column('cliente_estabelecimento', 'cep')
    op.drop_column('cliente_estabelecimento', 'bairro')
    op.drop_column('cliente_estabelecimento', 'numero')
    op.drop_column('cliente_estabelecimento', 'logradouro')
    op.drop_column('cliente_estabelecimento', 'codigo_cliente')
    op.drop_column('cliente_estabelecimento', 'pais_id')
    op.drop_column('cliente_estabelecimento', 'municipio_id')
    op.create_table(
        'estabelecimento',
        sa.Column('id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('active', sa.BOOLEAN(),
                  autoincrement=False, nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(),
                  autoincrement=False, nullable=True),
        sa.Column('created_by', sa.CHAR(length=32),
                  autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(),
                  autoincrement=False, nullable=True),
        sa.Column('updated_by', sa.CHAR(length=32),
                  autoincrement=False, nullable=True),
        sa.Column('tag', sa.VARCHAR(length=1000),
                  autoincrement=False, nullable=True),
        sa.Column('domain_id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('municipio_id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('pais_id', sa.CHAR(length=32),
                  autoincrement=False, nullable=True),
        sa.Column('codigo_cliente', sa.VARCHAR(length=10),
                  autoincrement=False, nullable=False),
        sa.Column('logradouro', sa.VARCHAR(length=255),
                  autoincrement=False, nullable=False),
        sa.Column('numero', sa.VARCHAR(length=60),
                  autoincrement=False, nullable=False),
        sa.Column('bairro', sa.VARCHAR(length=60),
                  autoincrement=False, nullable=False),
        sa.Column('cep', sa.VARCHAR(length=8),
                  autoincrement=False, nullable=False),
        sa.Column('complemento', sa.VARCHAR(length=60),
                  autoincrement=False, nullable=True),
        sa.Column('ponto_referencia', sa.VARCHAR(length=512),
                  autoincrement=False, nullable=True),
        sa.Column('tarefa_id', sa.CHAR(length=32),
                  autoincrement=False, nullable=False),
        sa.Column('custo_por_quilo', sa.NUMERIC(precision=17, scale=4),
                  server_default=sa.text('0.0'), autoincrement=False,
                  nullable=False),
        sa.Column('iluminacao_publica_media', sa.NUMERIC(precision=17, scale=4),
                  server_default=sa.text('0.0'), autoincrement=False,
                  nullable=False),
        sa.Column('custo_medio_energia', sa.NUMERIC(precision=17, scale=4),
                  server_default=sa.text('0.0'), autoincrement=False,
                  nullable=False),
        sa.Column('desconto_nominal', sa.NUMERIC(precision=17, scale=4),
                  server_default=sa.text('0.0'), autoincrement=False,
                  nullable=False),
        sa.Column(
            'tipo_calculo',
            postgresql.ENUM('DESCONTO_NOMINAL', 'CUSTO_POR_QUILO',
                            name='tipo_calculo'),
            autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['domain_id'], ['domain.id'],
            name='estabelecimento_domain_id_fkey'),
        sa.ForeignKeyConstraint(['tarefa_id'], [
            'tarefa.id'], name='estabelecimento_tarefa_id_fkey'),
        sa.ForeignKeyConstraint(
            ['municipio_id'], ['municipio.id'],
            name='estabelecimento_municipio_id_fkey'),
        sa.ForeignKeyConstraint(['pais_id'], ['pais.id'],
                                name='estabelecimento_pais_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='estabelecimento_pkey'),
        sa.UniqueConstraint(
            'domain_id', 'codigo_cliente', 'tarefa_id',
            name='estabelecimento_domain_id_codigo_cliente_tarefa_id_uk')
    )
    # ### end Alembic commands ###
