"""24.12.23 - remove parceiro

Revision ID: 89ce47c774b3
Revises: ca74e4542b46
Create Date: 2024-12-23 12:33:56.834380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89ce47c774b3'
down_revision = 'ca74e4542b46'
branch_labels = None
depends_on = None

def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefa_contato',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('tarefa_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('contato', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tarefa_id'], ['tarefa.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cliente_contato',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('contato', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cliente_endereco',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('logradouro', sa.String(
                        length=255), nullable=False),
                    sa.Column('numero', sa.String(length=60), nullable=False),
                    sa.Column('complemento', sa.String(
                        length=60), nullable=True),
                    sa.Column('bairro', sa.String(length=60), nullable=False),
                    sa.Column('ponto_referencia', sa.String(
                        length=512), nullable=True),
                    sa.Column('cep', sa.CHAR(length=8), nullable=False),
                    sa.Column('municipio_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('pais_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('cliente_id', sa.CHAR(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
                    sa.ForeignKeyConstraint(
                        ['municipio_id'], ['municipio.id'], ),
                    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tarefa_endereco',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('logradouro', sa.String(
                        length=255), nullable=False),
                    sa.Column('numero', sa.String(length=60), nullable=False),
                    sa.Column('complemento', sa.String(
                        length=60), nullable=True),
                    sa.Column('bairro', sa.String(length=60), nullable=False),
                    sa.Column('ponto_referencia', sa.String(
                        length=512), nullable=True),
                    sa.Column('cep', sa.CHAR(length=8), nullable=False),
                    sa.Column('municipio_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.Column('pais_id', sa.CHAR(length=32), nullable=True),
                    sa.Column('tarefa_id', sa.CHAR(
                        length=32), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tarefa_id'], ['tarefa.id'], ),
                    sa.ForeignKeyConstraint(
                        ['municipio_id'], ['municipio.id'], ),
                    sa.ForeignKeyConstraint(['pais_id'], ['pais.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('cliente_tarefa')
    op.add_column('cliente', sa.Column(
        'cpf_cnpj', sa.CHAR(length=14), nullable=False))
    op.add_column('cliente', sa.Column(
        'doc_estrangeiro', sa.CHAR(length=20), nullable=True))
    op.add_column('cliente', sa.Column(
        'rg_insc_est', sa.String(length=20), nullable=True))
    op.add_column('cliente', sa.Column('nome_razao_social',
                  sa.String(length=60), nullable=True))
    op.add_column('cliente', sa.Column('apelido_nome_fantasia',
                  sa.String(length=60), nullable=True))
    op.add_column('cliente', sa.Column(
        'observacao', sa.String(length=500), nullable=True))
    op.add_column('cliente', sa.Column(
        'data_nascimento', sa.DateTime(), nullable=True))
    op.drop_constraint('cliente_domain_id_codigo_uk', 'cliente', type_='unique')
    op.create_unique_constraint(
        'cliente_domain_id_tarefa_id_codigo_uk', 'cliente', [
            'domain_id', 'tarefa_id', 'codigo'])
    op.drop_constraint('cliente_id_fkey', 'cliente', type_='foreignkey')
    op.add_column('tarefa', sa.Column(
        'cpf_cnpj', sa.CHAR(length=14), nullable=True))
    op.add_column('tarefa', sa.Column(
        'doc_estrangeiro', sa.CHAR(length=20), nullable=True))
    op.add_column('tarefa', sa.Column(
        'rg_insc_est', sa.String(length=20), nullable=True))
    op.add_column('tarefa', sa.Column(
        'nome_razao_social', sa.String(length=60), nullable=True))
    op.add_column('tarefa', sa.Column(
        'apelido_nome_fantasia', sa.String(length=60), nullable=True))
    op.add_column('tarefa', sa.Column(
        'observacao', sa.String(length=500), nullable=True))
    op.add_column('tarefa', sa.Column(
        'data_nascimento', sa.DateTime(), nullable=True))
    op.drop_constraint('tarefa_id_fkey', 'tarefa', type_='foreignkey')

    session = create_session(op)
    session.execute("""
        UPDATE tarefa f
        SET cpf_cnpj = (SELECT cpf_cnpj FROM parceiro p
                        WHERE f.id=p.id);

        UPDATE tarefa f
        SET user_id = (SELECT user_id FROM parceiro p
                       WHERE f.id=p.id);
        """)

    op.drop_table('parceiro_endereco')
    op.drop_table('parceiro_contato')
    # op.drop_table('parceiro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tarefa_id_fkey',
                          'tarefa', 'parceiro', ['id'], ['id'])
    op.drop_column('tarefa', 'data_nascimento')
    op.drop_column('tarefa', 'observacao')
    op.drop_column('tarefa', 'apelido_nome_fantasia')
    op.drop_column('tarefa', 'nome_razao_social')
    op.drop_column('tarefa', 'rg_insc_est')
    op.drop_column('tarefa', 'doc_estrangeiro')
    op.drop_column('tarefa', 'cpf_cnpj')
    op.create_foreign_key('cliente_id_fkey', 'cliente',
                          'parceiro', ['id'], ['id'])
    op.drop_constraint(
        'cliente_domain_id_tarefa_id_codigo_uk', 'cliente', type_='unique')
    op.create_unique_constraint('cliente_domain_id_codigo_uk', 'cliente', [
                                'domain_id', 'codigo'])
    op.drop_column('cliente', 'data_nascimento')
    op.drop_column('cliente', 'observacao')
    op.drop_column('cliente', 'apelido_nome_fantasia')
    op.drop_column('cliente', 'nome_razao_social')
    op.drop_column('cliente', 'rg_insc_est')
    op.drop_column('cliente', 'doc_estrangeiro')
    op.drop_column('cliente', 'cpf_cnpj')
    op.create_table('parceiro_contato',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('tag', sa.VARCHAR(length=1000),
                              autoincrement=False, nullable=True),
                    sa.Column('parceiro_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('contato', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['parceiro_id'], ['parceiro.id'],
                        name='parceiro_contato_parceiro_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='parceiro_contato_pkey')
                    )
    op.create_table('cliente_tarefa',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('tag', sa.VARCHAR(length=1000),
                              autoincrement=False, nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('cliente_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('tarefa_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('nome', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=False),
                    sa.Column('observacao', sa.VARCHAR(length=100),
                              autoincrement=False, nullable=True),
                    sa.Column(
                        'custo_por_quilo', sa.NUMERIC(precision=23, scale=10),
                        server_default=sa.text('0.0'), autoincrement=False,
                        nullable=False),
                    sa.Column(
                        'iluminacao_publica_media', sa.NUMERIC(
                            precision=23, scale=10),
                        server_default=sa.text('0.0'), autoincrement=False,
                        nullable=False),
                    sa.Column(
                        'desconto_nominal', sa.NUMERIC(precision=23, scale=10),
                        server_default=sa.text('0.0'), autoincrement=False,
                        nullable=False),
                    sa.Column(
                        'preco_referencia', sa.NUMERIC(precision=23, scale=10),
                        server_default=sa.text('0.0'), autoincrement=False,
                        nullable=False),
                    sa.ForeignKeyConstraint(
                        ['cliente_id'], ['cliente.id'],
                        name='cliente_tarefa_cliente_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['domain_id'], ['domain.id'],
                        name='cliente_tarefa_domain_id_fkey'),
                    sa.ForeignKeyConstraint(['tarefa_id'], [
                        'tarefa.id'],
                        name='cliente_tarefa_tarefa_id_fkey'),
                    sa.PrimaryKeyConstraint(
                        'id', name='cliente_tarefa_pkey'),
                    sa.UniqueConstraint(
                        'domain_id', 'cliente_id', 'tarefa_id',
                        name='cliente_domain_id_cliente_id_tarefa_id_uk')
                    )
    op.create_table('parceiro',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('tag', sa.VARCHAR(length=1000),
                              autoincrement=False, nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('cpf_cnpj', sa.CHAR(length=14),
                              autoincrement=False, nullable=False),
                    sa.Column('doc_estrangeiro', sa.CHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.Column('rg_insc_est', sa.VARCHAR(length=20),
                              autoincrement=False, nullable=True),
                    sa.Column('nome_razao_social', sa.VARCHAR(length=60),
                              autoincrement=False, nullable=True),
                    sa.Column('apelido_nome_fantasia', sa.VARCHAR(
                        length=60), autoincrement=False, nullable=True),
                    sa.Column('observacao', sa.VARCHAR(length=500),
                              autoincrement=False, nullable=True),
                    sa.Column('data_nascimento', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['domain_id'], ['domain.id'],
                        name='parceiro_domain_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='parceiro_pkey'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('parceiro_endereco',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.BOOLEAN(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_at', postgresql.TIMESTAMP(),
                              autoincrement=False, nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('tag', sa.VARCHAR(length=1000),
                              autoincrement=False, nullable=True),
                    sa.Column('logradouro', sa.VARCHAR(length=255),
                              autoincrement=False, nullable=False),
                    sa.Column('numero', sa.VARCHAR(length=60),
                              autoincrement=False, nullable=False),
                    sa.Column('complemento', sa.VARCHAR(length=60),
                              autoincrement=False, nullable=True),
                    sa.Column('bairro', sa.VARCHAR(length=60),
                              autoincrement=False, nullable=False),
                    sa.Column('ponto_referencia', sa.VARCHAR(length=512),
                              autoincrement=False, nullable=True),
                    sa.Column('cep', sa.CHAR(length=8),
                              autoincrement=False, nullable=False),
                    sa.Column('municipio_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('pais_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('parceiro_id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['municipio_id'], ['municipio.id'],
                        name='parceiro_endereco_municipio_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['pais_id'], ['pais.id'],
                        name='parceiro_endereco_pais_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['parceiro_id'], ['parceiro.id'],
                        name='parceiro_endereco_parceiro_id_fkey'),
                    sa.PrimaryKeyConstraint('id', name='parceiro_endereco_pkey')
                    )
    op.drop_table('tarefa_endereco')
    op.drop_table('cliente_endereco')
    op.drop_table('cliente_contato')
    op.drop_table('tarefa_contato')
    # ### end Alembic commands ###
