"""25.01.29 - Add settings em Tarefa

Revision ID: 8bf51961ef8b
Revises: 3484a02b975f
Create Date: 2025-01-29 20:55:06.684296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf51961ef8b'
down_revision = '3484a02b975f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column(
        'settings', sa.Text(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefa', 'settings')
    # ### end Alembic commands ###
