"""25.03.24 - remove contraint de conta_receber para conta_energia ser única
nela

Revision ID: 9d0da325591c
Revises: 55b4bf535007
Create Date: 2025-03-24 19:01:24.942729

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '9d0da325591c'
down_revision = '55b4bf535007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'conta_receber_domain_id_tarefa_id_conta_energia_id_uk',
        'conta_receber', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'conta_receber_domain_id_tarefa_id_conta_energia_id_uk',
        'conta_receber', ['domain_id', 'tarefa_id', 'conta_energia_id'])
    # ### end Alembic commands ###
