"""24.10.26 - troca nomenclatura custo_medio_energia para preco_referencia

Revision ID: a32d69048866
Revises: 799c09cdadab
Create Date: 2024-10-26 10:38:08.311268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32d69048866'
down_revision = '799c09cdadab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cliente_estabelecimento', sa.Column('preco_referencia', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.drop_column('cliente_estabelecimento', 'custo_medio_energia')
    op.add_column(
        'cliente_tarefa', sa.Column('preco_referencia', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.drop_column('cliente_tarefa', 'custo_medio_energia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cliente_tarefa', sa.Column('custo_medio_energia', sa.NUMERIC(
            precision=17, scale=4), server_default=sa.text('0.0'),
            autoincrement=False, nullable=False))
    op.drop_column('cliente_tarefa', 'preco_referencia')
    op.add_column(
        'cliente_estabelecimento', sa.Column('custo_medio_energia', sa.NUMERIC(
            precision=17, scale=4), server_default=sa.text('0.0'),
            autoincrement=False, nullable=False))
    op.drop_column('cliente_estabelecimento', 'preco_referencia')
    # ### end Alembic commands ###
