"""24.10.16 - att estabelecimento e cliente_tarefa

Revision ID: c1afa37f6f06
Revises: 5005e823fd8d
Create Date: 2024-10-16 21:17:09.686108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1afa37f6f06'
down_revision = '5005e823fd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente_tarefa', sa.Column('custo_por_quilo', sa.Numeric(
        precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column(
        'cliente_tarefa', sa.Column('iluminacao_publica_media', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column(
        'cliente_tarefa', sa.Column('custo_medio_energia', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column(
        'cliente_tarefa', sa.Column('desconto_nominal', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column('estabelecimento', sa.Column(
        'tarefa_id', sa.CHAR(length=32), nullable=False))
    op.add_column('estabelecimento', sa.Column('custo_por_quilo', sa.Numeric(
        precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column(
        'estabelecimento', sa.Column('iluminacao_publica_media', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column(
        'estabelecimento', sa.Column('custo_medio_energia', sa.Numeric(
            precision=17, scale=4), server_default='0.0', nullable=False))
    op.add_column('estabelecimento', sa.Column('desconto_nominal', sa.Numeric(
        precision=17, scale=4), server_default='0.0', nullable=False))
    op.drop_constraint('estabelecimento_domain_id_codigo_cliente_uk',
                       'estabelecimento', type_='unique')
    op.create_unique_constraint(
        'estabelecimento_domain_id_codigo_cliente_tarefa_id_uk',
        'estabelecimento',
        ['domain_id', 'codigo_cliente', 'tarefa_id'])
    op.create_foreign_key('estabelecimento_tarefa_id_fkey',
                          'estabelecimento', 'tarefa',
                          ['tarefa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('estabelecimento_tarefa_id_fkey',
                       'estabelecimento', type_='foreignkey')
    op.drop_constraint(
        'estabelecimento_domain_id_codigo_cliente_tarefa_id_uk',
        'estabelecimento', type_='unique')
    op.create_unique_constraint(
        'estabelecimento_domain_id_codigo_cliente_uk', 'estabelecimento',
        ['domain_id', 'codigo_cliente'])
    op.drop_column('estabelecimento', 'desconto_nominal')
    op.drop_column('estabelecimento', 'custo_medio_energia')
    op.drop_column('estabelecimento', 'iluminacao_publica_media')
    op.drop_column('estabelecimento', 'custo_por_quilo')
    op.drop_column('estabelecimento', 'tarefa_id')
    op.alter_column('cliente_tarefa', 'cliente_id',
                    existing_type=sa.CHAR(length=32),
                    nullable=False)
    op.drop_column('cliente_tarefa', 'desconto_nominal')
    op.drop_column('cliente_tarefa', 'custo_medio_energia')
    op.drop_column('cliente_tarefa', 'iluminacao_publica_media')
    op.drop_column('cliente_tarefa', 'custo_por_quilo')
    # ### end Alembic commands ###
