"""24.12.18 - refatoracao de parceiro, cliente, e tarefa

Revision ID: ca74e4542b46
Revises: b226a301d63f
Create Date: 2024-12-18 22:02:34.882041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca74e4542b46'
down_revision = 'b226a301d63f'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    session = create_session(op)
    session.execute("""
        DELETE FROM conta_energia;
        DELETE FROM cliente_estabelecimento;
        DELETE FROM cliente_tarefa;
        DELETE FROM cliente;
        """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('tarefa_id',
                  sa.CHAR(length=32), nullable=False))
    op.add_column('cliente', sa.Column('custo_por_quilo', sa.Numeric(
        precision=23, scale=10), server_default='0.0', nullable=False))
    op.add_column('cliente', sa.Column('iluminacao_publica_media', sa.Numeric(
        precision=23, scale=10), server_default='0.0', nullable=False))
    op.add_column('cliente', sa.Column('preco_referencia', sa.Numeric(
        precision=23, scale=10), server_default='0.0', nullable=False))
    op.add_column('cliente', sa.Column('desconto_nominal', sa.Numeric(
        precision=23, scale=10), server_default='0.0', nullable=False))
    op.create_foreign_key('cliente_tarefa_id_fkey', 'cliente', 'tarefa',
                          ['tarefa_id'], ['id'])
    op.add_column('tarefa', sa.Column(
        'user_id', sa.CHAR(length=32), nullable=True))
    op.create_unique_constraint('tarefa_user_id_uk', 'tarefa',
                                ['user_id'])
    op.create_foreign_key('tarefa_user_id_fkey', 'tarefa', 'user',
                          ['user_id'], ['id'])
    op.drop_constraint('parceiro_domain_id_cpf_cnpj_uk',
                       'parceiro', type_='unique')
    op.drop_constraint('parceiro_domain_id_doc_estrangeiro_uk',
                       'parceiro', type_='unique')
    op.drop_constraint('parceiro_domain_id_rg_insc_est_uk',
                       'parceiro', type_='unique')
    op.drop_constraint('parceiro_user_id_key', 'parceiro', type_='unique')
    op.drop_constraint('parceiro_user_id_fkey', 'parceiro', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('parceiro_user_id_fkey',
                          'parceiro', 'user', ['user_id'], ['id'])
    op.create_unique_constraint('parceiro_user_id_key', 'parceiro', ['user_id'])
    op.create_unique_constraint('parceiro_domain_id_rg_insc_est_uk', 'parceiro', [
                                'domain_id', 'rg_insc_est'])
    op.create_unique_constraint('parceiro_domain_id_doc_estrangeiro_uk',
                                'parceiro', ['domain_id', 'doc_estrangeiro'])
    op.create_unique_constraint('parceiro_domain_id_cpf_cnpj_uk', 'parceiro', [
                                'domain_id', 'cpf_cnpj'])
    op.drop_constraint('tarefa_user_id_fkey', 'tarefa',
                       type_='foreignkey')
    op.drop_constraint('tarefa_user_id_uk', 'tarefa', type_='unique')
    op.drop_column('tarefa', 'user_id')
    op.drop_constraint('cliente_tarefa_id_fkey',
                       'cliente', type_='foreignkey')
    op.drop_column('cliente', 'desconto_nominal')
    op.drop_column('cliente', 'preco_referencia')
    op.drop_column('cliente', 'iluminacao_publica_media')
    op.drop_column('cliente', 'custo_por_quilo')
    op.drop_column('cliente', 'tarefa_id')
    # ### end Alembic commands ###
