"""24.10.23 - add tipo_calculo em estabelecimento

Revision ID: e3d42760c444
Revises: c1afa37f6f06
Create Date: 2024-10-23 20:18:33.964504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d42760c444'
down_revision = 'c1afa37f6f06'
branch_labels = None
depends_on = None


def create_session(op):
    from sqlalchemy.orm import sessionmaker

    _session = sessionmaker()
    bind = op.get_bind()
    session = _session(bind=bind)

    return session


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimento', sa.Column('tipo_calculo', sa.Enum(
        'DESCONTO_NOMINAL', 'CUSTO_POR_QUILO', name='tipo_calculo'),
        nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimento', 'tipo_calculo')
    # ### end Alembic commands ###

    session = create_session(op)
    session.execute("DROP TYPE IF EXISTS tipo_calculo;")
