"""24.08.01 - add tabela conta_energia

Revision ID: e8e62c818a50
Revises: 16cb6c7d753f
Create Date: 2024-08-01 18:40:10.844281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e62c818a50'
down_revision = '16cb6c7d753f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
                    sa.Column('id', sa.CHAR(length=32), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['file_infosys.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('conta_energia',
                    sa.Column('id', sa.CHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.CHAR(length=32), nullable=True),
                    sa.Column('tag', sa.String(length=1000), nullable=True),
                    sa.Column('domain_id', sa.CHAR(length=32), nullable=False),
                    sa.Column('documento_id', sa.CHAR(
                        length=32), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['documento_id'], ['documento.id'], ),
                    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conta_energia')
    op.drop_table('documento')
    # ### end Alembic commands ###
