"""25.04.07 - add flag de valor_multa em porcentagem ou não

Revision ID: f0912074ec63
Revises: 58c39ab10930
Create Date: 2025-04-07 23:02:04.222196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0912074ec63'
down_revision = '58c39ab10930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('valor_multa_padrao_porcentagem',
                  sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('cliente', 'valor_multa_padrao')
    op.add_column('cliente', sa.Column('valor_multa_padrao',
                  sa.NUMERIC(precision=23, scale=10),
                  server_default='0.0', nullable=False))
    op.add_column('conta_receber', sa.Column('valor_multa_porcentagem',
                  sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conta_receber', 'valor_multa_porcentagem')
    op.alter_column('cliente', 'valor_multa_padrao',
                    existing_type=sa.NUMERIC(precision=23, scale=10),
                    nullable=True)
    op.drop_column('cliente', 'valor_multa_padrao_porcentagem')
    # ### end Alembic commands ###
