# Generated by Django 6.0.4 on 2026-04-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_type_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skipped_in',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ignorada em'),
        ),
    ]
