# Generated by Django 6.0.4 on 2026-04-25 00:00

from django.db import migrations, models


def backfill_time_spent(apps, schema_editor):
    Task = apps.get_model('tasks', 'Task')
    for task in Task.objects.filter(time_spent__isnull=True, started_in__isnull=False, finished_in__isnull=False):
        task.time_spent = task.finished_in - task.started_in
        task.save(update_fields=['time_spent'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.DurationField(blank=True, editable=False, null=True, verbose_name='tempo gasto'),
        ),
        migrations.RunPython(backfill_time_spent, noop_reverse),
    ]
