# Generated by Django 6.0.4 on 2026-05-04 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('possible_tasks', '0004_possibletask_project'),
        ('tasks', '0010_remove_task_execution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='origin_possible_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_task', to='possible_tasks.possibletask', verbose_name='possível tarefa de origem'),
        ),
    ]
