# Generated by Django 6.0.4 on 2026-10-06 14:43

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=160)),
                ('position', models.PositiveSmallIntegerField()),
                ('target_sets', models.PositiveSmallIntegerField()),
                ('target_repetitions', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('is_skipped', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
            ],
            options={
                'verbose_name': 'Exercício da sessão',
                'verbose_name_plural': 'Exercícios da sessão',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SessionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='série')),
                ('repetitions', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='repetições realizadas')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peso (kg)')),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('session_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.sessionexercise')),
            ],
            options={
                'verbose_name': 'Série realizada',
                'verbose_name_plural': 'Séries realizadas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(verbose_name='data final')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('is_archived', models.BooleanField(default=False, verbose_name='arquivado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia da semana')),
                ('position', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ordem')),
                ('sets_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='séries')),
                ('repetitions', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='repetições por série')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Exercício do treino',
                'verbose_name_plural': 'Exercícios do treino',
                'ordering': ['weekday', 'position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=160)),
                ('scheduled_weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('date', models.DateField(verbose_name='data')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('partial', 'Parcial')], default='in_progress', max_length=20, verbose_name='situação')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Sessão de treino',
                'verbose_name_plural': 'Sessões de treino',
                'ordering': ['-started_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutsession'),
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='workouts_unique_exercise_name'),
        ),
        migrations.AddConstraint(
            model_name='sessionset',
            constraint=models.UniqueConstraint(fields=('session_exercise', 'number'), name='workouts_unique_set_number'),
        ),
        migrations.AddConstraint(
            model_name='sessionset',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1)), name='workouts_positive_set_number'),
        ),
        migrations.AddConstraint(
            model_name='sessionset',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__isnull', True), _connector='OR'), name='workouts_nonnegative_weight'),
        ),
        migrations.AddConstraint(
            model_name='sessionset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('registered_at__isnull', True), ('repetitions__isnull', True), ('weight__isnull', True)), models.Q(('registered_at__isnull', False), ('repetitions__isnull', False), ('weight__isnull', False)), _connector='OR'), name='workouts_complete_set_record'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='workouts_one_active_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='workouts_valid_date_range'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('is_active', True), ('is_archived', True), _negated=True), name='workouts_archived_not_active'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='workouts_valid_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('repetitions__gte', 1), ('sets_count__gte', 1)), name='workouts_positive_plan'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['owner', 'date'], name='workouts_wo_owner_i_1f9b61_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('owner',), name='workouts_one_open_session'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_weekday__lte', 6)), name='workouts_valid_session_weekday'),
        ),
    ]
