# Generated by Django 6.0.4 on 2026-10-06 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workout',
            name='workouts_valid_date_range',
        ),
        migrations.AlterField(
            model_name='workout',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='data final'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='workouts_valid_date_range'),
        ),
    ]
