# Generated by Django 6.0.4 on 2026-10-06 15:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_workouts_valid_date_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(3600)], verbose_name='descanso entre séries (segundos)'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='rest_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MaxValueValidator(3600)]),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('rest_seconds__lte', 3600)), name='workouts_valid_rest_seconds'),
        ),
        migrations.AddConstraint(
            model_name='workoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('rest_seconds__lte', 3600)), name='workouts_valid_session_rest'),
        ),
    ]
