# Generated by Django 6.0.4 on 2026-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_tasks', '0002_tempo_estimado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='task_type',
            field=models.CharField(choices=[('task', 'Tarefa'), ('objective', 'Objetivo')], default='task', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='estimated_time',
            field=models.DurationField(blank=True, null=True, verbose_name='tempo estimado'),
        ),
    ]
