# Generated by Django 6.0.4 on 2026-04-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring_tasks', '0003_recurringtask_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], default=1, verbose_name='prioridade'),
        ),
    ]
