# Generated by Django 6.0.4 on 2026-10-06 21:12

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de compras',
                'verbose_name_plural': 'Listas de compras',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'verbose_name': 'Item da feira',
                'verbose_name_plural': 'Itens da feira',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=160, verbose_name='Lista')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada em')),
                ('status', models.CharField(choices=[('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='in_progress', max_length=16, verbose_name='Situação')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor total (R$)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_sessions', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='shopping.shoppinglist')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingSessionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Item')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppingsession')),
                ('source_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopping.shoppingitem')),
            ],
            options={
                'verbose_name': 'Item comprado',
                'verbose_name_plural': 'Itens comprados',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='shoppingitem',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('shopping_list'), name='shopping_unique_item_name'),
        ),
        migrations.AddConstraint(
            model_name='shoppingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('owner',), name='shopping_one_open_session'),
        ),
        migrations.AddConstraint(
            model_name='shoppingsession',
            constraint=models.CheckConstraint(condition=models.Q(('total__isnull', True), ('total__gte', 0), _connector='OR'), name='shopping_nonnegative_total'),
        ),
        migrations.AddConstraint(
            model_name='shoppingsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'in_progress'), ('total__isnull', True)), models.Q(('finished_at__isnull', False), ('status', 'completed'), ('total__isnull', False)), models.Q(('finished_at__isnull', False), ('status', 'cancelled'), ('total__isnull', True)), _connector='OR'), name='shopping_valid_session_state'),
        ),
        migrations.AddConstraint(
            model_name='shoppingsessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__isnull', True), ('quantity__gte', 0), _connector='OR'), name='shopping_nonnegative_quantity'),
        ),
    ]
